---
Title: "UBCO Research Data Hub"
pagetitle: "UBCO Research Data Hub"
output:
  html_document:
    includes:
      in_header: header.html
---
```{r, setup, include = F}
knitr::opts_chunk$set(
  echo = F,
  warning = F,
  message = F
)
```
## Workshops

All workshops are series based, beginning at the introductory level for those with absolutely no experience, and building up to more advanced concepts.  Individual workshops are scheduled for roughly 1 hour, with 30 minutes of instructor led content, 15 minutes for Q&A related to the content, and 15 monutes for follow up if needed.  Each workshop has its own webpage with the full content of the session, with the intention of having resources for people to revisit after a session, as well as to self-instruct.

All workshop listings and materials can be found [here](https://csc-ubc-okanagan.github.io/workshops/)

Workshop schedule and registration can be found [here](https://csc.ok.ubc.ca/workshops/)

## R & Python Blog

If you are looking for a quick answer to a specific question regarding R and Python, our R & Python Blog addresses common data issues and data analysis tasks in bite size, question-informed bits. If you find yourself with a question that has not been answered by the blog posts currently available, we encourage you to book a consultation with our Data Consultants.

The R & Python Blog posts can be found [here](https://csc-ubc-okanagan.github.io/R-Python-Blog/) 

## Data Consultations

Once you have developed competency with the workshop materials, it's possible that you have questions about how to apply the generic concepts covered in those sessions to the specific aspects of your research project.  To accomodate this, we have free one-on-one bookable sessions with our Data Consultants, that specialize in a variety of approaches for working with research data including Python, R, etc. for data visualization, modelling, statistical analysis, and many other topics related to preparing and analyzing research data from a broad spectrum of disciplines. Consultations are available to those with all levels of experience, but we do ask that you familiarize yourself with the workshop content prior to booking, as these sessions are meant to move a step beyond this content.

To learn more and book a consult [here](visit: https://csc.ok.ubc.ca/consultations/research-data-consultation/)
